variables:
  poolImage: "ubuntu-latest"
  poolPythonVersion: 3.6
  FreezeFileStem: 'requirements-freeze-predeploy'

trigger: none # No CI build

pr: none # Not for pull requests


stages:
- stage: CreateWheel
  pool:
    vmImage: $(PoolImage)

  jobs:
  - job: 'Create_Wheel'

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
        addToPath: true
    
    - template: templates/python-infra-upgrade-steps-template.yml

    - script: pip install setuptools wheel 
      displayName: 'Install setuptools'

    - script: pip install -r requirements.txt
      displayName: "Install fairlearn requirements"

    - script: python ./scripts/build_widget.py --yarn-path /usr/bin/yarn
      displayName: 'Build widget'
      condition: false

    - script: python setup.py sdist bdist_wheel
      displayName: 'Build Wheel'

    - task: PublishPipelineArtifact@1
      displayName: "Publish wheel to artifact"
      inputs:
        path: $(System.DefaultWorkingDirectory)/dist
        artifact: 'Wheel'

# ============================================================================

- stage: TestWheel
  pool:
    vmImage: $(PoolImage)

  jobs:
  - job: 'Test_Wheel'

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.6'
      inputs:
        versionSpec: 3.6
        addToPath: true
    
    - template: templates/python-infra-upgrade-steps-template.yml

    - template: templates/python-infra-upgrade-steps-template.yml

    - template: templates/requirements-installation-steps-template.yml
      parameters:
        pyVer: '3.6'
        requirementsFile: 'requirements.txt'
        pinRequirements: false

    - template: templates/install-fairlearn-wheel-artifact-step-template.yml
      parameters:
        fairlearnWheelArtifactName: "Wheel"

    - script: python -m pytest test/unit/metrics/
      displayName: "Run some quick tests"